# Generated by Django 3.2.8 on 2024-06-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField()),
                ('month', models.CharField(max_length=100)),
                ('days_present', models.IntegerField()),
            ],
        ),
    ]
