# Generated by Django 3.2.8 on 2024-06-03 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPayofmonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_pay', models.IntegerField()),
                ('empno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.empattendence')),
            ],
        ),
    ]
