# Generated by Django 3.2.8 on 2024-06-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0003_alter_basicpayofmonth_empno'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField()),
                ('it_perc', models.IntegerField()),
            ],
        ),
    ]
